/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CuadrosIndexRouteImport } from './routes/cuadros.index'
import { Route as CuadrosIdRouteImport } from './routes/cuadros.$id'

const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuadrosIndexRoute = CuadrosIndexRouteImport.update({
  id: '/cuadros/',
  path: '/cuadros/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuadrosIdRoute = CuadrosIdRouteImport.update({
  id: '/cuadros/$id',
  path: '/cuadros/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cuadros/$id': typeof CuadrosIdRoute
  '/cuadros/': typeof CuadrosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cuadros/$id': typeof CuadrosIdRoute
  '/cuadros': typeof CuadrosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cuadros/$id': typeof CuadrosIdRoute
  '/cuadros/': typeof CuadrosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacto' | '/cuadros/$id' | '/cuadros/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/cuadros/$id' | '/cuadros'
  id: '__root__' | '/' | '/contacto' | '/cuadros/$id' | '/cuadros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  CuadrosIdRoute: typeof CuadrosIdRoute
  CuadrosIndexRoute: typeof CuadrosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuadros/': {
      id: '/cuadros/'
      path: '/cuadros'
      fullPath: '/cuadros/'
      preLoaderRoute: typeof CuadrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuadros/$id': {
      id: '/cuadros/$id'
      path: '/cuadros/$id'
      fullPath: '/cuadros/$id'
      preLoaderRoute: typeof CuadrosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  CuadrosIdRoute: CuadrosIdRoute,
  CuadrosIndexRoute: CuadrosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
