/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CuadrosRouteImport } from './routes/cuadros'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CuadrosIdRouteImport } from './routes/cuadros.$id'

const CuadrosRoute = CuadrosRouteImport.update({
  id: '/cuadros',
  path: '/cuadros',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuadrosIdRoute = CuadrosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CuadrosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cuadros': typeof CuadrosRouteWithChildren
  '/cuadros/$id': typeof CuadrosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cuadros': typeof CuadrosRouteWithChildren
  '/cuadros/$id': typeof CuadrosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cuadros': typeof CuadrosRouteWithChildren
  '/cuadros/$id': typeof CuadrosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacto' | '/cuadros' | '/cuadros/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/cuadros' | '/cuadros/$id'
  id: '__root__' | '/' | '/contacto' | '/cuadros' | '/cuadros/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  CuadrosRoute: typeof CuadrosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cuadros': {
      id: '/cuadros'
      path: '/cuadros'
      fullPath: '/cuadros'
      preLoaderRoute: typeof CuadrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuadros/$id': {
      id: '/cuadros/$id'
      path: '/$id'
      fullPath: '/cuadros/$id'
      preLoaderRoute: typeof CuadrosIdRouteImport
      parentRoute: typeof CuadrosRoute
    }
  }
}

interface CuadrosRouteChildren {
  CuadrosIdRoute: typeof CuadrosIdRoute
}

const CuadrosRouteChildren: CuadrosRouteChildren = {
  CuadrosIdRoute: CuadrosIdRoute,
}

const CuadrosRouteWithChildren =
  CuadrosRoute._addFileChildren(CuadrosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  CuadrosRoute: CuadrosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
